site_name: Jennifer Smith's Portfolio
nav:
  - Home: index.md

  - Marketing:
    - visuals.md

  - NIH NCBI Samples:
    - Tecnical Writing: documentation-samples.md
    - QA.md
    



  - Learning New Tech: 

    - yaml.md
    - webcrawler.md

  - Websites: 
     - Websites: visuals/#websites

theme: readthedocs

   
