site_name: Jennifer Smith's Portfolio
nav:
  - Home: index.md

  - Marketing:
    - visuals.md

  - NIH NCBI Samples:
    - Tecnical Writing: documentation-samples.md
    - QA.md
    



  - Learning New Tech: 

    - yaml.md
    - webcrawler.md

  - Websites I Made: 
    - Portfolio Website 2014: jenniferpetroffsmith.me/jps/index.html
    - Portfolio Website 2012: jenniferpetroffsmith.md/secondcup/index.htm 
    - Actor's Website 2010: jenniferpetroffsmith.me/rwsmith3/index.html 

theme: readthedocs

   
