site_name: Jennifer Smith's Portfolio
nav:
  - Home: index.md

  - NIH NCBI Writing Samples:
    - documentation-samples.md
    - QA.md
    - QA.md

  - Personal Efforts: 
    - webcrawler.md
    - yaml.md


theme: readthedocs
