site_name: Jennifer Smith's Portfolio
nav:
  - Home: index.md

  - docs:
    - professional-documentation-samples.md
    - Dynamics-QA.md
 
  - Personal efforts: 
    - webcrawler.md
    - yaml.md

theme: readthedocs
