site_name: Jennifer Smith's Portfolio
nav:
  - Home: index.md

  - NIH NCBI Samples:
    - Documentation Samples: documentation-samples.md
    - QA.md
    
  - Organizational Communications:
    - visuals.md


  - Learning New Tech: 

    - yaml.md
    - webcrawler.md

  - Resume: 
    - resume.md

theme: readthedocs

   
