site_name: Jennifer Smith's Portfolio
extra_css:
  - css/custom.css
nav:
  - Home: index.md

  
  - Content Samples:
    - visuals.md


 

  - NIH NCBI Samples:
    - Tecnical Writing Samples: documentation-samples.md
    - QA.md

  - Learning New Tech: 
    - api.md
    - webcrawler.md


theme: readthedocs

   
