site_name: Jennifer Smith's Portfolio
nav:
  - Home: index.md

  - NIH NCBI Samples:
    - NCBI: documentation-samples.md
    - QA.md
    
  - Marketing:
    - visuals.md


  - Learning New Tech: 

    - yaml.md
    - webcrawler.md

  - Resumes: 
    - resume.md

theme: readthedocs

   
