site_name: Jennifer Smith's Portfolio
nav:
  - Home: index.md

  - NIH NCBI Writing Samples:
    - documentation-samples.md
    - QA.md
    
  - Organizational Communications:
    - visuals.md

  - Learning New Tech: 
    - webcrawler.md
    - yaml.md

theme: readthedocs

extra_css:
  - extra.css   
