site_name: Jennifer Smith's Portfolio
nav:
  - Home: index.md

  

  - NIH NCBI Samples:
    - Tecnical Writing: documentation-samples.md
    - QA.md


  - Learning New Tech: 

    - yaml.md
    - webcrawler.md

  - Marketing:
    - visuals.md

theme: readthedocs

   
