site_name: Jennifer Smith's Portfolio
nav:
  - Home: index.md

  
  - Learning New Tech: 
    - api.md
    - webcrawler.md

  - NIH NCBI Samples:
    - Tecnical Writing Samples: documentation-samples.md
    - QA.md


  - Marketing:
    - visuals.md

theme: readthedocs

   
