site_name: Jennifer Smith's Portfolio
nav:
  - Home: index.md

  - docs:
    - documentation-samples.md
    - QA.md
    - webcrawler.md
 
  - Personal efforts: 
    - webcrawler.md
    - yaml.md

theme: readthedocs
